# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
platform :android do

  # Run all test
  desc "Run all tests"
  lane :test do
    gradle(task: 'test')
  end


  # Firebase app distribution
  desc "Firebase App distribution"
  lane :beta do
    gradle(
        task: 'assemble',
        build_type: 'Release'
    )
    firebase_app_distribution(
        app: "1:410639833159:android:567bfa2984bdf9419bb962",
        release_notes: "first release",
        testers: "alexmumoit12@gmail.com"
    )
  end
end
